{"name": "Проверка возврата ошибки 404 при попытке логина с неверным паролем", "status": "passed", "steps": [{"name": "Генерация данных для логина курьера с возмождностью подмены значений", "status": "passed", "parameters": [{"name": "key", "value": "'password'"}, {"name": "value", "value": "'9999'"}], "start": 1717960332145, "stop": 1717960332146}, {"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "data", "value": "{'login': 'Din', 'password': '9999'}"}], "start": 1717960332146, "stop": 1717960332237}], "start": 1717960332145, "stop": 1717960332238, "uuid": "e3a427cc-0920-451a-a82b-cccedbb8997e", "historyId": "098088fe8b0cfd14ac19f68487f51375", "testCaseId": "098088fe8b0cfd14ac19f68487f51375", "fullName": "tests.test_login_courier.TestLoginCourier#test_wrong_password_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "0000NBB03CJLVCF"}, {"name": "thread", "value": "610-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}